Add WSL 2 + Docker introduction
unity3d-jp/Unity-ROS-MobileRobot-UI-Tutorial pull request #21
Opened 2022-06-30 09:59 UTC by Tiryoh

Docker Desktopを使わず、WSL 2に直接Dockerをインストールして使う場合の方法について記載しました

2022-06-30 10:52 UTC, comoc requested changes
@Tiryoh DockerのSevice Agreementについての記述に関して修正いただけないでしょうか？

2022-06-30 10:52 UTC, comoc commented on docs/intro3.md
> +> 4.2 Specific License Limitations – Docker Desktop.
ここの引用に関してですが、他社のサービスへの深入りした言及は避けたいため、以下のような一文に留めて、

> 詳細については関連リンクをご参照ください。

関連リンクの中に、下記を追加するように出来ればと思うのですが、いかがでしょうか？

https://www.docker.com/legal/docker-subscription-service-agreement/

2022-07-01 10:22 UTC, Tiryoh commented on docs/intro3.md
> +> 4.2 Specific License Limitations – Docker Desktop.
https://github.com/unity3d-jp/Unity-ROS-MobileRobot-UI-Tutorial/pull/21/commits/90b409886cf18fa2a16ed1e13feee70b3fbf6dfc
修正しました。こちらでいかがでしょう？

2022-07-01 10:39 UTC, comoc commented on docs/intro3.md
> +> 4.2 Specific License Limitations – Docker Desktop.
ありがとうございます。問題ないことを確認しました。

2022-07-01 10:39 UTC, merged